[build]
command = "dotnet restore RoadMonitoringSystem/RoadMonitoringSystem.csproj && dotnet publish RoadMonitoringSystem/RoadMonitoringSystem.csproj --no-restore -c Release -o out"

[start]
command = "./out/RoadMonitoringSystem"
